@startuml

rectangle "Grammaire" as grammar
rectangle "AST" as ast
rectangle "Règles" as rules
rectangle "PREMIER" as first
rectangle "Collection LR(1)" as lr1
rectangle "Collection LALR" as lalr
rectangle "Table LALR" as table

grammar -> ast : <i>parsing</i>
ast --> rules : <i>transformation</i>
first <- rules : <i>construction</i>
rules --> lr1 : <i>génération</i>
first --> lr1
lr1 --> lalr : <i>fusion</i>
lalr -> table : <i>construction</i>

note right of lr1
  items set 0:
    C => * c C $, c / d
    C => * d $, c / d
    S => * C C $, $
    __start => * S $, $
end note

@enduml
