@startuml

rectangle "Table LALR" as table
rectangle "Contexte" as context #Yellow
rectangle "Compilation" as compile
rectangle "<i>Template</i>" as template #Yellow
rectangle "Sortie" as output

table -- context
context --> compile
template -> compile
compile -> output

@enduml
